apiVersion: v1
kind: Service
metadata:
  name: produto-service
spec:
  selector:
    app: produto-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer


